<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMz6Q8vC\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMz6Q8vC/ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMz6Q8vC.legacy');

    return;
}

if (!\class_exists(ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMz6Q8vC\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerMz6Q8vC\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'Mz6Q8vC',
    'container.build_id' => '4365de35',
    'container.build_time' => 1637854306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMz6Q8vC');
