<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6TXXreM\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6TXXreM/ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6TXXreM.legacy');

    return;
}

if (!\class_exists(ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\Container6TXXreM\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \Container6TXXreM\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => '6TXXreM',
    'container.build_id' => 'b41f7857',
    'container.build_time' => 1637853878,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6TXXreM');
