<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx0nw1v\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx0nw1v/ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerUx0nw1v.legacy');

    return;
}

if (!\class_exists(ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerUx0nw1v\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer::class, false);
}

return new \ContainerUx0nw1v\ControllerKnpU_LoremIpsumBundle_Tests_Controller_KnpULoremIpsumControllerKernelTestDebugContainer([
    'container.build_hash' => 'Ux0nw1v',
    'container.build_id' => 'cafdbfc0',
    'container.build_time' => 1637853666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx0nw1v');
