<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZPw3xnF\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZPw3xnF/testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZPw3xnF.legacy');

    return;
}

if (!\class_exists(testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZPw3xnF\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \ContainerZPw3xnF\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => 'ZPw3xnF',
    'container.build_id' => '0ad2fddf',
    'container.build_time' => 1637850348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZPw3xnF');
