<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8QOx6rE\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8QOx6rE/testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8QOx6rE.legacy');

    return;
}

if (!\class_exists(testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\Container8QOx6rE\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer::class, false);
}

return new \Container8QOx6rE\testsKnpU_LoremIpsumBundle_Tests_KnpULoremIpsumTestingKernelTestDebugContainer([
    'container.build_hash' => '8QOx6rE',
    'container.build_id' => '5fe47fcf',
    'container.build_time' => 1637851428,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8QOx6rE');
